general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 0

[window]
decorations = "None"

[mouse]
hide_when_typing = true
